apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
  labels:
    {{- include "envoy-edge.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.envoyConfigs }}
  {{$key }}: |-
    {{- $value | nindent 4 }}
{{- end }}
    