{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "envoy-edge.fullname" . }}
  labels:
    {{- include "envoy-edge.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
    verbs: ["get", "list", "watch"]
{{- end }}