{{- if .Values.tlsSecret.data -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "envoy-edge.fullname" . }}
{{- if .Values.tlsSecret.annotations }}
  annotations:
{{ toYaml .Values.tlsSecret.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "envoy-edge.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.tlsSecret.data }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end -}}
{{- end -}}