apiVersion: v1
kind: Service
metadata:
  name: {{ include "envoy-edge.fullname" . }}
  labels:
    {{- include "envoy-edge.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.name }}
    {{- if .Values.service.ports }}
    {{- range $port := .Values.service.ports }}
    - port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
      protocol: {{ $port.protocol }}
      name: {{ $port.name }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "envoy-edge.selectorLabels" . | nindent 4 }}
