apiVersion: v1
kind: Service
metadata:
  name: {{ include "envoy-edge.fullname" . }}
  labels:
    {{- include "envoy-edge.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: proxy
    - port: 9901
      targetPort: 9901
      protocol: TCP
      name: http-admin
  selector:
    {{- include "envoy-edge.selectorLabels" . | nindent 4 }}
